FROM quay.io/icgc-argo/dna-seq-processing-tools:base-docker.0.2.0

LABEL org.opencontainers.image.source https://github.com/icgc-argo/demo-wfpkgs

ENV PATH="/tools:${PATH}"

COPY *.py /tools/

CMD ["/bin/bash"]


